# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_pract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello_pract.Score'),
        ),
    ]
